# variaveis
CC=g++
LIBS= -lGL -lglut -lGLU
EXEC=exec_ex
CPP=braco_ex.cpp

# codigo base
C=gcc
# LIB_BASE= -lGLU
EXEC_BASE=exec_aux
C_CODE= cod_base_braco.c

ex:
	$(CC) $(CPP) -o $(EXEC) $(LIBS)

base:
	$(C) $(C_CODE) -o $(EXEC_BASE) $(LIBS) 